execute pathogen#infect()
syntax on
filetype plugin indent on

" editor settings
set nu
set tabstop=4
set autoindent
set clipboard=unnamedplus
set mouse=a
set smarttab
set shiftwidth=4
set softtabstop=4
set smartcase

" mappings
nmap <leader>y ggVG"+y''

" templates
:autocmd BufNewFile *.c 0r ~/.vim/templates/c-template.c
:autocmd BufNewFile *.cpp 0r ~/.vim/templates/cpp-template.cpp
:autocmd BufNewFile *.java 0r ~/.vim/templates/java-template.java
:autocmd BufNewFile *.py 0r ~/.vim/templates/py-template.py
:autocmd BufNewFile *.sh 0r ~/.vim/templates/sh-template.sh

" compilation and run key bindings
autocmd filetype cpp nnoremap <F5> :<C-U>!g++ -O2 -DLOCAL -std=c++17 -Wshadow -Wall -Wextra -Wno-unused-result -static %:r.cpp -o %:r<CR>
autocmd filetype cpp nnoremap <F6> :<C-U>!g++ -std=c++17 -Wshadow -Wall -o -g -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG %:r.cpp -o %:r<CR>
autocmd filetype cpp nnoremap <F9> :<C-U>!./%:r<CR>
autocmd filetype python nnoremap <F5> :w <bar> !python3 % <CR>
autocmd filetype java nnoremap <F5> :<C-U>!javac %:r.java<CR>
autocmd filetype java nnoremap <F9> :exec '!java Main'<cr>
autocmd filetype sh nnoremap <F9> :<C-U>!bash %:r.sh<CR>
autocmd filetype javascript nnoremap <F9> :<C-U>!node %:r.js<CR>

" nerd tree
map <C-n> :NERDTreeToggle<CR>
